# creating a static build of the website
FROM node:12-alpine as build
WORKDIR /web
ENV REACT_APP_API_URL /api
COPY package*.json ./

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm ci --only=production \
    && apk del build-dependencies

COPY . .
RUN npm run build

# exposing website via nginx webserver
FROM nginx:1.17-alpine
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /web/build /usr/share/nginx/html
COPY --from=build /web/homepage /var/homepage
EXPOSE 80
