version: '3.7'

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: karma-postgres
    environment:
      POSTGRES_DB: karma-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd123
    ports:
      - 5432:5432
  server:
    image: karma/server
    build:
      context: ../../../server
      dockerfile: ../resources/docker/Dockerfile
    container_name: karma-server
    ports:
      - 8000:8000
    depends_on:
      - db
    command: sh -c "npm run db-migrate up && node server.js"

volumes:
  db_data: {}
