version: '3.7'

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: karma-postgres
    environment:
      POSTGRES_DB: karma-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd123
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: karma/server
    build:
      context: ../../../server
      dockerfile: ../resources/docker/Dockerfile.server
    container_name: karma-server
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "npm run db-migrate up && node server.js"]

  admin:
    image: karma/admin
    build:
      context: ../../../admin
      dockerfile: ../resources/docker/Dockerfile.admin
    container_name: karma-admin
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  db_data: {}
