name: Backend - Automatically Run Node.js Tests

# Trigger on push or pull request
on: 
  push:
    branches:         # == run tests only on push to following branches: ==
      - master        # master
      - dev           # dev
      - 'be**'        # any branch prefixed 'be', e.g. 'be-my-feature'
      - 'backend**'   # any branch prefix 'backend', e.g. 'backend/my-feature'
    paths:
      - 'server/**'  # limit workflow tests only to changes in backend folder
  pull_request:
    branches:         # == run tests only on pull requests to: ==
      - master        # master
      - dev           # dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [12.x] # build for current LTS Node.JS version, 12.x

    # setup node, build, and run tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # Show MOTD:
    - run: base64 -d <<<"H4sIAA1RO14AA1NQAINH0zpAaOp0ZCaUBUdYhNBFQQYo4NUBFOJSQLV0Ipw15dHUuUjsCSAE00ZAHLuFUyfi0obmCIQOkBuw+RPZNAwNCDaaFB6NYHH0sJiC7EZUUYQETk8hFEydhc15uDRiOGMiUjrAIjYRvxjIdpD5c/FrgFsKV45gkiGmQEAp0DpbWwWnxOTs1LwUhZDU4pJiBV0FZ0+F4pLEvJRihbT8IgV15/z8HAXPvJLU9KLEksz8PHWQHi4AZpk6ziYDAAA=" | gunzip
    
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    
    - run: echo Backend CI Workflow Complete

# For help, see:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
