name: Backend - Automatically Run Node.js Tests

# Trigger on push or pull request
on:
  push:
    branches: # == run tests only on push to following branches: ==
      - master # master (rerun tests after merging a PR)
    paths:
      - "server/**" # limit workflow tests only to changes in backend folder
  pull_request:
    branches: # == run tests only on pull request opens/updates to: ==
      - master
      - dev # dev
    paths:
      - "server/**"

jobs:
  # build and run tests
  build:
    runs-on: ubuntu-latest
    # setup node, build, and run tests
    steps:
      - name: checkout Github repo
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: initialize app
        run: base64 -d <<<"H4sIAA1RO14AA1NQAINH0zpAaOp0ZCaUBUdYhNBFQQYo4NUBFOJSQLV0Ipw15dHUuUjsCSAE00ZAHLuFUyfi0obmCIQOkBuw+RPZNAwNCDaaFB6NYHH0sJiC7EZUUYQETk8hFEydhc15uDRiOGMiUjrAIjYRvxjIdpD5c/FrgFsKV45gkiGmQEAp0DpbWwWnxOTs1LwUhZDU4pJiBV0FZ0+F4pLEvJRihbT8IgV15/z8HAXPvJLU9KLEksz8PHWQHi4AZpk6ziYDAAA=" | gunzip

      - name: npm install
        working-directory: ./server
        run: npm i --ignore-scripts

      - name: npm build
        working-directory: ./server
        run: npm run build --if-present

      - name: run ESLint
        uses: ninosaurus/eslint-check@v5
        with:
          eslint-config-path: "./server/.eslintrc.js"
          custom-directory: "./server"
          repo-token: ${{secrets.GITHUB_TOKEN}}

  # validate code style with eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Github repo
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: initialize app
        run: base64 -d <<<"H4sIAA1RO14AA1NQAINH0zpAaOp0ZCaUBUdYhNBFQQYo4NUBFOJSQLV0Ipw15dHUuUjsCSAE00ZAHLuFUyfi0obmCIQOkBuw+RPZNAwNCDaaFB6NYHH0sJiC7EZUUYQETk8hFEydhc15uDRiOGMiUjrAIjYRvxjIdpD5c/FrgFsKV45gkiGmQEAp0DpbWwWnxOTs1LwUhZDU4pJiBV0FZ0+F4pLEvJRihbT8IgV15/z8HAXPvJLU9KLEksz8PHWQHi4AZpk6ziYDAAA=" | gunzip

      - name: npm install
        working-directory: ./server
        run: npm i --ignore-scripts

      - name: npm test
        run: npm test
        working-directory: ./server
        env:
          CI: true

# For help, see:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
