name: Backend

# Trigger on push or pull request
on:
  push:
    branches: # == run tests only on push to following branches: ==
      - master # master (rerun tests after merging a PR)
    paths:
      - "server/**" # limit workflow tests only to changes in backend folder
  pull_request:
    branches: # == run tests only on pull request opens/updates to: ==
      - master
      - dev # dev
    paths:
      - "server/**"
      - "resources/**"

jobs:
  # build and run tests
  build:
    runs-on: ubuntu-latest
    # setup node, build, and run tests
    steps:
      - name: checkout GitHub repo
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        working-directory: ./server
        run: npm ci

      - name: TEST
        working-directory: ./server
        run: echo ${{github.ref}}

      - name: Generate docs
        if: github.ref == 'refs/pull/127/merge' # TODO Change this to 'refs/heads/dev' before merging
        run: npm run docs
        working-directory: ./server
      - name: Deploy docs
        if: github.ref == 'refs/pull/127/merge' # TODO Change this to 'refs/heads/dev' before merging
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "server/out"
          target: "web-data"
